input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  mutate {
      lowercase => ["service_name"]
    }

  if [service_name] {
    mutate {
      add_field => { "[@metadata][index]" => "%{service_name}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{service_name}-%{+YYYY.MM.dd}"
    action => "create"
    data_stream => false
  }
  stdout {
    codec => rubydebug
  }
}